(function(){
'use strict';
const C=window.EDUCORE_CONFIG||{}; const root=document.getElementById('app');
const money=n=>'UGX '+Number(n||0).toLocaleString(); const date=d=>d?new Date(d+'T00:00:00').toLocaleDateString('en-GB'):'';
let sb=null,session=null,parent=null,children=[],selected=null,data={attendance:[],payments:[],results:[],reports:[],notifications:[],messages:[],school:null},view='home';
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function shell(){return `<header><div class="brand"><div class="logo">E</div><div><b>${esc(data.school?.name||'EduCore')}</b><span>Parent Portal</span></div></div><div class="actions"><button class="icon" id="refresh">↻</button><button class="icon" id="signout">⇥</button></div></header><main id="main"></main><nav class="bottom">${[['home','⌂','Home'],['children','♙','Children'],['attendance','✓','Attendance'],['fees','₵','Fees'],['results','▣','Results'],['messages','✉','Messages']].map(x=>`<button data-view="${x[0]}" class="${view===x[0]?'active':''}"><i>${x[1]}</i>${x[2]}</button>`).join('')}</nav>`}
function login(){root.innerHTML=`<div class="login"><div class="card loginCard"><div class="brand"><div class="logo">E</div><div><b>EduCore</b><span>Parent Portal</span></div></div><h1>Welcome back</h1><p class="muted">Sign in to monitor your child or children.</p><form id="login"><label>Email<input id="email" type="email" required autocomplete="email"></label><label>Password<input id="password" type="password" required autocomplete="current-password"></label><div id="err"></div><button class="primary">Sign in</button></form><button class="link" id="reset">Forgot password?</button></div></div>`;document.getElementById('login').onsubmit=async e=>{e.preventDefault();const err=document.getElementById('err');err.innerHTML='';const b=e.submitter;b.disabled=true;b.textContent='Signing in…';const r=await sb.auth.signInWithPassword({email:email.value,password:password.value});if(r.error)err.innerHTML=`<div class="error">${esc(r.error.message)}</div>`;b.disabled=false;b.textContent='Sign in'};document.getElementById('reset').onclick=async()=>{const e=document.getElementById('email').value;if(!e)return alert('Enter your email first.');const r=await sb.auth.resetPasswordForEmail(e,{redirectTo:location.href});alert(r.error?r.error.message:'Password reset email sent.')}}
async function load(){document.getElementById('main').innerHTML='<div class="center"><div class="spinner"></div></div>';const uid=session.user.id;let r=await sb.from('parents').select('*').eq('user_id',uid).maybeSingle();if(r.error)throw r.error;if(!r.data){parent=null;showAccountError();return}parent=r.data;let links=await sb.from('parent_student_links').select('student_id').eq('parent_id',parent.id).eq('status','Active');let ids=(links.data||[]).map(x=>x.student_id);if(!ids.length){const legacy=await sb.from('students').select('id').eq('parent_id',parent.id).eq('status','Active');ids=(legacy.data||[]).map(x=>x.id)};if(!ids.length){children=[];data={...data,school:null};selected=null;render();return}let [st,att,pay,res,rep]=await Promise.all([sb.from('students').select('*,classes:class_id(id,name),streams:stream_id(id,name)').in('id',ids).eq('status','Active'),sb.from('attendance').select('*').in('student_id',ids).order('date',{ascending:false}),sb.from('payments').select('*').in('student_id',ids).order('payment_date',{ascending:false}),sb.from('results').select('*,exams:exam_id(name,academic_year,term,is_published),subjects:subject_id(name)').in('student_id',ids).eq('is_published',true),sb.from('report_cards').select('*').in('student_id',ids).eq('is_published',true).order('created_at',{ascending:false})]);if(st.error)throw st.error;children=st.data||[];selected=selected&&children.some(c=>c.id===selected.id)?selected:children[0];const sid=children[0].school_id;const [school,notifs,msgs]=await Promise.all([sb.from('schools').select('*').eq('id',sid).maybeSingle(),sb.from('notifications').select('*').eq('school_id',sid).in('target_role',['All','Parent']).order('created_at',{ascending:false}).limit(30),sb.from('parent_messages').select('*').eq('school_id',sid).eq('parent_id',parent.id).order('created_at',{ascending:false}).limit(50)]);data={attendance:att.data||[],payments:pay.data||[],results:res.data||[],reports:rep.data||[],notifications:notifs.data||[],messages:msgs.data||[],school:school.data||null};render()}
function showAccountError(){root.innerHTML=`<div class="center"><div class="card setup"><div class="logo">E</div><h2>Parent account setup needed</h2><p class="muted">Your login is not linked to a parent record yet. Ask the school administrator to set the parent <b>user_id</b> to your Supabase Auth user ID and link your children.</p><button class="primary" id="out">Sign out</button></div></div>`;document.getElementById('out').onclick=signout}
function render(){root.innerHTML=shell();const main=document.getElementById('main');main.innerHTML=`<div class="welcome"><div><small>WELCOME BACK</small><h1>${esc(parent.full_name)}</h1><p class="muted">Monitor attendance, fees, results and school communication.</p></div></div>${children.length?`<div class="picker"><label>Viewing child<select id="child">${children.map(c=>`<option value="${c.id}" ${selected?.id===c.id?'selected':''}>${esc(c.first_name+' '+c.last_name)} — ${esc(c.classes?.name||'Class not set')}</option>`).join('')}</select></label><span>${children.length} linked ${children.length===1?'child':'children'}</span></div>`:''}${page()}`;document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});document.getElementById('refresh').onclick=load;document.getElementById('signout').onclick=signout;const cp=document.getElementById('child');if(cp)cp.onchange=()=>{selected=children.find(c=>c.id===cp.value);render()}}
function page(){if(view==='home')return home();if(view==='attendance')return attendance();if(view==='fees')return fees();if(view==='results')return results();if(view==='messages')return messages();if(view==='children')return childrenPage();return home()}
function current(){return selected||children[0];}function childRows(k){const c=current();return data[k].filter(x=>x.student_id===c?.id)}
function home(){const c=current();if(!c)return `<div class="empty"><h2>No children linked</h2><p>Ask the school office to link your children.</p></div>`;const a=childRows('attendance'),p=childRows('payments'),r=childRows('reports'),present=a.filter(x=>x.status==='Present').length,pct=a.length?Math.round(present/a.length*100):0;return `<section class="hero"><div><small>SELECTED CHILD</small><h2>${esc(c.first_name+' '+c.last_name)}</h2><p>${esc(c.admission_number||c.student_id_number)} · ${esc(c.classes?.name||'Class not set')}${c.streams?.name?' · '+esc(c.streams.name):''}</p></div><div class="avatar">${esc(c.first_name[0])}</div></section><div class="grid"><div class="stat"><span>Attendance</span><b>${pct}%</b><small>${present} present of ${a.length}</small></div><div class="stat"><span>Payments</span><b>${money(p.reduce((s,x)=>s+Number(x.amount_ugx||0),0))}</b><small>${p.length} recorded</small></div><div class="stat"><span>Latest average</span><b>${r[0]?.average_marks!=null?r[0].average_marks+'%':'—'}</b><small>${r[0]?esc(r[0].term):'No published report'}</small></div><div class="stat"><span>Messages</span><b>${data.messages.length}</b><small>School messages</small></div></div><div class="section"><h2>Quick access</h2><div class="quick"><button data-view="attendance">✓ Attendance</button><button data-view="fees">₵ Fees</button><button data-view="results">▣ Results</button><button data-view="messages">✉ Messages</button></div></div><div class="section"><h2>Latest notices</h2>${data.notifications.slice(0,4).map(n=>`<article class="notice"><b>${esc(n.title)}</b><p>${esc(n.message)}</p><small>${new Date(n.created_at).toLocaleDateString('en-GB')}</small></article>`).join('')||'<div class="emptySmall">No notices yet.</div>'}</div>`}
function attendance(){const a=childRows('attendance');return `<section class="page"><h2>Attendance</h2><p class="muted">${esc(current()?.first_name||'')}</p><div class="grid four">${['Present','Absent','Late','Excused'].map(s=>`<div class="stat"><span>${s}</span><b>${a.filter(x=>x.status===s).length}</b><small>Recorded days</small></div>`).join('')}</div><div class="table"><table><thead><tr><th>Date</th><th>Status</th><th>Reason</th></tr></thead><tbody>${a.map(x=>`<tr><td>${date(x.date)}</td><td><span class="pill ${x.status.toLowerCase()}">${x.status}</span></td><td>${esc(x.reason||'—')}</td></tr>`).join('')}</tbody></table>${!a.length?'<div class="emptySmall">No attendance records available.</div>':''}</div></section>`}
function fees(){const p=childRows('payments'),r=childRows('reports');return `<section class="page"><h2>Fees & payments</h2><p class="muted">${esc(current()?.first_name||'')}</p><div class="grid two"><div class="stat"><span>Recorded payments</span><b>${money(p.reduce((s,x)=>s+Number(x.amount_ugx||0),0))}</b><small>${p.length} payments</small></div><div class="stat"><span>Current balance</span><b>${r[0]?.fees_balance_ugx!=null?money(r[0].fees_balance_ugx):'Contact school'}</b><small>Latest published report</small></div></div><div class="table"><table><thead><tr><th>Date</th><th>Receipt</th><th>Method</th><th>Reference</th><th>Amount</th></tr></thead><tbody>${p.map(x=>`<tr><td>${date(x.payment_date)}</td><td>${esc(x.receipt_number)}</td><td>${esc(x.payment_method)}</td><td>${esc(x.transaction_reference||'—')}</td><td>${money(x.amount_ugx)}</td></tr>`).join('')}</tbody></table>${!p.length?'<div class="emptySmall">No payment records available.</div>':''}</div></section>`}
function results(){const r=childRows('results'),cards=childRows('reports');return `<section class="page"><h2>Academic results</h2><p class="muted">${esc(current()?.first_name||'')}</p>${cards.map(x=>`<article class="report"><div><b>${esc(x.academic_year)} · ${esc(x.term)}</b><p>${esc(x.teacher_remarks||'Published report card')}</p></div><strong>${x.average_marks!=null?x.average_marks+'%':'—'}</strong></article>`).join('')}<div class="table"><table><thead><tr><th>Exam</th><th>Subject</th><th>Marks</th><th>Grade</th><th>Remarks</th></tr></thead><tbody>${r.map(x=>`<tr><td>${esc(x.exams?.name||'Exam')}</td><td>${esc(x.subjects?.name||'Subject')}</td><td>${x.marks_obtained}</td><td>${esc(x.grade)}</td><td>${esc(x.remarks||'—')}</td></tr>`).join('')}</tbody></table>${!r.length?'<div class="emptySmall">No published results available.</div>':''}</div></section>`}
function messages(){return `<section class="page"><h2>School communication</h2><p class="muted">Messages sent to your parent account</p>${data.messages.map(x=>`<article class="message"><b>${esc(x.subject||'School message')}</b><small>${new Date(x.created_at).toLocaleString('en-GB')}</small><p>${esc(x.message)}</p></article>`).join('')||'<div class="empty">No messages yet.</div>'}</section>`}
function childrenPage(){return `<section class="page"><h2>My children</h2><p class="muted">Children linked to your parent account</p><div class="children">${children.map(c=>`<button class="childCard ${selected?.id===c.id?'selected':''}" data-id="${c.id}"><div class="avatar small">${esc(c.first_name[0])}</div><div><b>${esc(c.first_name+' '+c.last_name)}</b><span>${esc(c.classes?.name||'Class not set')}</span><small>${esc(c.admission_number||c.student_id_number)}</small></div></button>`).join('')||'<div class="empty">No children linked yet.</div>'}</div></section>`}
async function signout(){await sb.auth.signOut();session=null;parent=null;login()}
function setup(){if(!C.supabaseUrl||!C.supabaseAnonKey){root.innerHTML=`<div class="center"><div class="card setup"><div class="logo">E</div><h1>EduCore Parent Portal</h1><h2>Supabase configuration required</h2><p class="muted">Open <b>config.js</b> and replace the empty values with the URL and anon key from the same Supabase project used by EduCore.</p><pre>window.EDUCORE_CONFIG={
 supabaseUrl:'https://YOUR-PROJECT.supabase.co',
 supabaseAnonKey:'YOUR_ANON_KEY'
};</pre></div></div>`;return}sb=window.supabase.createClient(C.supabaseUrl,C.supabaseAnonKey);sb.auth.getSession().then(async r=>{session=r.data.session;if(session){try{await load()}catch(e){root.innerHTML=`<div class="center"><div class="card setup"><h2>Could not load EduCore</h2><p>${esc(e.message)}</p><button class="primary" id="try">Try again</button></div></div>`;document.getElementById('try').onclick=load}}else login()});sb.auth.onAuthStateChange((_e,s)=>{session=s;if(!s)login()})}
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));setup();
})();
